###############Makefile###############

CC = gcc
CFLAGS = -O2 -Wall

pessoas: pessoas.o pessoas_funcoes.o

pessoas.o: pessoas.h pessoas.c

pessoas_func.o: pessoas.h pessoas_funcoes.c

clean:
	rm -f *.o pessoas     
